### ISSUE TITLE
Import fails with numpy 1.16.2 and python 3.7.2 for gvar >= 11.11.3

### ISSUE THREAD

**Issue by cmorsbach** [gplepage/gvar#42] opened 2023-09-07 13:25 UTC
I'm running gvar on HPC ressources with an older version of numpy (1.16.2).

Since gvar 11.11.3 it cannot be imported anymore with numpy 1.16.2:

```python
Traceback (most recent call last):
  File "post.py", line 25, in <module>
    import gvar as gv
  File "[...]/lib/python3.7/site-packages/gvar/__init__.py", line 123, in <module>
    from ._gvarcore import *
  File "src/gvar/_gvarcore.pyx", line 1, in init gvar._gvarcore
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

I have no idea, what the problem is and if there is an easy fix.

A solution would be to require a newer numpy version for gvar.

**Comment by gplepage** [comment] 2023-09-09 02:00
Thanks for flagging this issue. This probably reflects the changing relationship between cython and numpy. Do you know what version of cython was installed on the system?

I think I know how to fix  this but I won't be able to get to it for a week or so.

**Comment by cmorsbach** [comment] 2023-09-11 07:00
Thanks for the quick reply! This is the cython version:

```python
>>> import cython
>>> cython.__version__
'0.29.6'
```

Would really appreciate a fix, thank you! There is no need for hurry! 😄

**Comment by gplepage** [comment] 2023-09-21 14:02
The problem arises because I switched to Python's modern build tools (since the old tools are disappearing from up-to-date systems). These tools create their own environment within which to build the module and then transfer the built module to your system. The build environment uses up-to-date versions of numpy and cython, by default, but these are incompatible with the older numpy installed in your system.

I don't know of an easy fix for gvar that avoids this problem in all cases, but there is a trivial workaround that can be used when the problem arises. This is to modify the pyproject.toml file to include version numbers for numpy and cython. 

Try the following: First download a fresh copy of the current gvar from github. Then replace the contents of the pyproject.toml file with:
```
[build-system]
requires = ["setuptools", "numpy==1.16.2", "cython==0.29.6"]
build-backend = 'setuptools.build_meta'
```
Then install from gvar's home directory (``python -m pip . --no-cache-dir`` or ``make install``).

**Comment by gplepage** [comment] 2023-09-21 15:39
There seems to be a simpler solution: Install gvar using
```
pip install gvar --no-cache-dir --no-build-isolation
```
The ``--no-build-isolation`` causes it to use what is installed in your system for numpy and cython. This fixed the problem on my machine.

**Comment by cmorsbach** [comment] 2023-09-25 07:38
Thanks for the suggestions! Indeed, our package which requires gvar is still configured using a `setup.py`. I was thinking about migrating it to `pyproject.toml`. Do you think this might also fix the problem? I would like to avoid having to introduce special treatment for the gvar requirement. Ideally, I'd just like to require gvar and let pip figure it all out. 😄

**Comment by gplepage** [comment] 2023-09-26 18:18
I think I have a solution to this problem. I should have an updated version of ``gvar`` up within a day or so.

**Comment by cmorsbach** [comment] 2023-09-26 18:27
Cool, thanks a lot! Just give me a heads up and I'll try it out.

**Comment by gplepage** [comment] 2023-09-27 20:15
gvar version 11.11.14 should fix this problem. 

The problem is fixed by having the build use the oldest supported version of numpy for whatever version of Python is being used. This means that the version of numpy used to build the module will be the same or older than what is on the system, and therefore compatible with it (since numpy is backwards compatible). The precise version of numpy is chosen by the oldest-supported-numpy module.

**Comment by gplepage** [comment] 2023-09-28 02:19
Use gvar version 11.11.15.

**Comment by cmorsbach** [comment] 2023-10-09 20:04
Well, that seems to fix it on my side! Sorry for the late reply and thank you very much for your help!

**Comment by gplepage** [comment] 2023-10-09 20:21
Great! And thanks again for flagging the issue.

**Closed by gplepage** 2023-10-09 20:21 UTC
