### ISSUE TITLE
np.array of gvars is not np.einsummable

### ISSUE THREAD

**Issue by evanberkowitz** [gplepage/gvar#21] opened 2022-03-15 23:22 UTC
[`np.einsum`](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.einsum.html#numpy.einsum) is a convenient way to do contractions of tensor of data.

While writing [this example cross-correlation fitter](https://github.com/gplepage/lsqfit/issues/11) I tried to use `einsum` rather than the quadruply-nested for loop in `fcn`.  The issue can be shown with a simpler example

`einsum-issue.py`:
```python
#!/usr/bin/env python

import numpy as np
import gvar as gv

x = 2

n = np.array([[i+j for i in range(x)] for j in range(x)])
g = np.array([[gv.gvar(f'{i+j}({(i+j)/2})') for i in range(x)] for j in range(x)])

print(n)
print(g)

nn = np.einsum('ij,jk->ik',n,n)

print(nn)

ng = np.einsum('ij,jk->ik',n,g)
gn = np.einsum('ij,jk->ik',g,n)
gg = np.einsum('ij,jk->ik',g,g)
```

which outputs
```
[[0 1]
 [1 2]]
[[0(0) 1.00(50)]
 [1.00(50) 2.0(1.0)]]
[[1 2]
 [2 5]]
Traceback (most recent call last):
  File "./einsum-issue.py", line 18, in <module>
    ng = np.einsum('ij,jk->ik',n,g)
  File "<__array_function__ internals>", line 5, in einsum
  File "/path/to/python3.8/site-packages/numpy/core/einsumfunc.py", line 1361, in einsum
    return c_einsum(*operands, **kwargs)
TypeError: invalid data type for einsum
```

where we see the `dtype=float` `np.array` gave the expected matrix-matrix multiplication.  All the `einsum`s which try to act on `g` fail with the same `TypeError`.

Is it possible to use `np.einsum` on combinations of arrays of floats and gvars?  What would need to be done to unlock this possibility?

**Comment by gplepage** [comment] 2022-03-16 03:46
``einsum`` also doesn't work if you set the data type of an array of floats equal to ``object``: eg,
```
a = np.array(np.arange(25.).reshape(5,5), dtype=object)
np.einsum('ii', a)
```
generates the same error. The problem is that the ``numpy`` people haven't gotten around to supporting ``dtype=object`` for ``einsum`` the way they have for most other similar ``numpy`` functions.

So ``einsum`` needs to be changed if you want to use ``GVar``s since they are ``dtype=object``.

**Comment by evanberkowitz** [comment] 2022-03-16 07:02
Aha.  So this issue will be resolved when https://github.com/numpy/numpy/issues/17837 is resolved, and isn't about `gvar` at all.

**Comment by Gattocrucco** [comment] 2022-04-21 13:18
I just ran into the same problem, and I found the following solution.

The library [opt_einsum](https://github.com/dgasmith/opt_einsum) supports summing object dtypes.

```python
import numpy as np
import gvar
import opt_einsum

M = gvar.gvar(np.zeros(10000), np.ones(10000)).reshape(100, 100)
X = opt_einsum.contract('ij,ij,kl->kl', M, M, M, backend='object')
print(X)
```
```
[[0(0) 0(0) 0(0) ... 0(0) 0(0) 0(0)]
 [0(0) 0(0) 0(0) ... 0(0) 0(0) 0(0)]
 [0(0) 0(0) 0(0) ... 0(0) 0(0) 0(0)]
 ...
 [0(0) 0(0) 0(0) ... 0(0) 0(0) 0(0)]
 [0(0) 0(0) 0(0) ... 0(0) 0(0) 0(0)]
 [0(0) 0(0) 0(0) ... 0(0) 0(0) 0(0)]]
```

However this is somewhat slow because it is implemented in Python:

```python
%timeit opt_einsum.contract('ij,ij,kl->kl', M, M, M, backend='object')
```
```
76 ms ± 2.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

A trick to force `opt_einsum` to switch to numpy loops while still supporting object dtypes is providing a mock-up backend. Write a file `oebackend.py` in the current directory with these contents

```python
# oebackend.py
from numpy import tensordot, transpose
```

Then use it as backend in `opt_einsum.contract`:

```python
%timeit opt_einsum.contract('ij,ij,kl->kl', M, M, M, backend='oebackend')
```
```
4.42 ms ± 18.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

So about 20x faster.

This is necessary because by default `opt_einsum.contract` finds `numpy.einsum` and tries to use it. The mockup module `oebackend` provides only `tensordot` and `transpose` forcing the algorithm not to rely on `einsum`. However this will work only when there are indices which are not summed over alone or contracted with more than one other index.

**Comment by Gattocrucco** [comment] 2022-04-21 21:36
Another solution: in simple cases (all those in your initial example), passing the argument ``optimize=True`` makes ``np.einsum`` work on object dtypes

**Comment by gplepage** [comment] 2022-11-02 15:48
I am doing housecleaning and am going to close this thread because the problem is in ``einsum`` not ``gvar``. Also a couple of workarounds are suggested above.

**Closed by gplepage** 2022-11-02 15:48 UTC
